# Generated by Django 2.0 on 2018-01-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='Retro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Description')),
                ('action_item', models.CharField(max_length=200, verbose_name='Action Item')),
                ('status', models.CharField(choices=[('O', 'Open'), ('I', 'In-Progress'), ('C', 'Complete')], max_length=1)),
                ('eta', models.DateField(verbose_name='ETA')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Owner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.BigIntegerField(verbose_name='Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, verbose_name='Team')),
            ],
        ),
        migrations.AddField(
            model_name='retro',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Sprint'),
        ),
        migrations.AddField(
            model_name='retro',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Team'),
        ),
    ]
