# Generated by Django 2.0 on 2017-12-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50, verbose_name='Owner')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='Project Name')),
            ],
        ),
        migrations.CreateModel(
            name='RetroDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('action_item', models.CharField(max_length=200, verbose_name='Action Item')),
                ('eta', models.DateField(verbose_name='ETA')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Owner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.BigIntegerField(verbose_name='Sprint')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, verbose_name='Team')),
            ],
        ),
        migrations.AddField(
            model_name='retrodetails',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Sprint'),
        ),
        migrations.AddField(
            model_name='retrodetails',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Status'),
        ),
        migrations.AddField(
            model_name='retrodetails',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retro.Team'),
        ),
    ]
