# Generated by Django 2.0 on 2017-12-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status',
            new_name='status_item',
        ),
    ]
