# Generated by Django 2.0 on 2017-12-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0004_auto_20171227_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RetroDetails',
            new_name='Retro',
        ),
    ]
