# Generated by Django 2.0 on 2017-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0005_auto_20171227_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='sprint_number',
            field=models.CharField(max_length=50, verbose_name='Sprint'),
        ),
    ]
