# Generated by Django 2.0 on 2017-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retro', '0006_auto_20171228_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='sprint_number',
            field=models.BigIntegerField(verbose_name='Sprint'),
        ),
    ]
